# -*- coding: utf-8 -*-
"""Conteúdo original das apostilas do Curso Fusca Original.
Foco no Fusca brasileiro; fatos apurados em pesquisa. Texto de autoria própria."""

MODULOS = []

# ============================ MÓDULO 1 ============================
MODULOS.append({
 "file":"modulo1.html","pill":"Módulo 1 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 1","title_hi":"Identificação & Datação",
 "sub":"Como descobrir, com segurança, o ano e a identidade real de um Fusca",
 "foot_left":"Fusca alemão e brasileiro · 1950–1986 / 1993–1996",
 "sections":[
  ("h2","1.0","Por que datar e identificar vem primeiro"),
  ("lead","Antes de falar em parachoque, cor ou motor original, é preciso responder a uma pergunta: que Fusca é esse, afinal — e de que ano ele realmente é?"),
  ("p","Toda avaliação de originalidade parte da <strong>identidade correta do carro</strong>. Um item só é \"original\" quando você sabe <em>original de quê</em>: de que ano, de que versão, de que fase de produção."),
  ("box","ex","Exemplo","Um parachoque com \"bananinhas\" (sobre-guarnições) é certíssimo num Fusca 1975, mas errado num 1965 — que usava parachoque reto e liso. O mesmo item, \"original\" num carro e \"errado\" no outro. Sem datar primeiro, é impossível avaliar."),
  ("p","Neste módulo você aprende a ler o \"RG\" do Fusca — seus vários números de fábrica — e a separar três coisas que muita gente confunde: <strong>ano de fabricação</strong>, <strong>ano/modelo</strong> e <strong>ano do documento</strong>."),
  ("h2","1.1","Os sete números do Fusca"),
  ("p","Um Fusca de fábrica carrega <strong>vários números</strong>, cada um contando uma parte da história. Decore onde ficam."),
  ("table",["Número","Onde fica"],[
    ["<strong>Chassi</strong> (o principal)","batido no túnel central, sob o banco traseiro, junto à tampa de inspeção do câmbio"],
    ["<strong>Plaqueta de identificação</strong>","no berço do estepe (atrás do pneu sobressalente); traz ano, chassi, capacidade de carga e Tipo"],
    ["<strong>Número da carroceria</strong>","logo abaixo da plaqueta de identificação (fase clássica)"],
    ["<strong>Número do motor</strong>","no próprio bloco, visível ao abrir a tampa traseira"],
    ["<strong>Caixa de câmbio</strong>","gravado na carcaça da transmissão; costuma só aparecer com o câmbio removido"],
    ["<strong>Suspensão dianteira</strong>","lado direito do quadro, no tubo que sustenta o batente de borracha"],
    ["<strong>Ano e Tipo</strong>","estampados/pinados na própria plaqueta de identificação"]]),
  ("box","dica","Dica de originalidade","O número da <strong>suspensão dianteira</strong> é um teste silencioso: só os quadros originais de fábrica o possuem. Se ele não estiver mais lá, o quadro da dianteira foi trocado."),
  ("h2","1.2","A regra de ouro: chassi = plaqueta"),
  ("p","O número do chassi (no túnel, sob o banco traseiro) <strong>deve ser exatamente o mesmo</strong> que consta na plaqueta de identificação (atrás do estepe). Conferir se os dois batem é a <strong>verificação mais importante que existe</strong> antes de comprar qualquer Fusca."),
  ("box","ex","Exemplo de conferência","Você lê no túnel <span class=\"mono\">BS-1-234567</span> e a plaqueta diz o mesmo número. ✔️ Identidade coerente. Se a plaqueta trouxesse outro número, seria alerta vermelho — plaqueta trocada ou identidade adulterada."),
  ("p","O motor é caso à parte: por ser a peça que mais troca de carro na vida de um Fusca, o número do motor <strong>raramente \"casa\"</strong> com o chassi — e isso, por si só, não é problema. Ele revela o <em>tipo/geração</em> do propulsor (Módulo 4)."),
  ("box","atencao","Atenção · os três \"anos\"","O <strong>ano do documento</strong> (CRLV) nem sempre reflete o carro real. Um Fusca fabricado em novembro pode já ser <strong>ano/modelo</strong> do ano seguinte, e o documento pode estar defasado. <strong>Datar pela chapa resolve a ambiguidade.</strong>"),
  ("h2pb","1.3","A marcação do chassi no túnel conta a época"),
  ("p","Antes de ler o número, a <strong>forma como ele foi gravado</strong> no túnel já ajuda a datar o carro — detalhe precioso e difícil de falsificar:"),
  ("table",["Período","Como o número aparece no túnel"],[
    ["1949 a março/1952","número pinado <strong>sobre um ressalto</strong> (saliência) do túnel"],
    ["março/1952 a 1955","número dentro de um pequeno <strong>rebaixo</strong>, feito para proteger a marcação"],
    ["a partir de 1956 (± janeiro)","local do túnel passa a ser <strong>totalmente liso</strong>"]]),
  ("fotos",["FOTO: número no túnel sobre ressalto (1949–52)","FOTO: número no túnel liso (a partir de 1956)"]),
  ("box","ex","Exemplo de datação sem documento","Um vendedor jura que o carro é 1953, mas o número está sobre um <strong>ressalto</strong> saliente — que sumiu em março de 1952. Ou o carro é anterior, ou o assoalho foi enxertado. A chapa entrega o que o papel esconde."),
  ("h3","O número do motor também evoluiu"),
  ("p","Até 1949, a numeração do motor ficava <strong>acima</strong> da inscrição <span class=\"mono\">Zündfolge 1-4-3-2</span> (a ordem de explosão dos cilindros). De 1949/1950 em diante, passou para <strong>abaixo</strong> dessa inscrição."),
  ("h2","1.4","As eras da plaqueta de identificação"),
  ("p","A plaqueta é uma linha do tempo em metal. Corte importante: as regras clássicas valem <strong>até o início de 1964</strong> (até o chassi <span class=\"mono\">B4-142.238</span>); depois disso mudam a posição da plaqueta e do número da carroceria."),
  ("h3","Era alemã e início nacional (1950–1959)"),
  ("ul",["Plaqueta de <strong>ferro</strong>, cabeçalho <span class=\"mono\">Volkswagenwerk G.m.b.H</span>, campos em alemão.",
         "Fixada por <strong>4 rebites de ferro de cabeça lisa</strong> (não é rebite pop).",
         "Chassi (a partir do <span class=\"mono\">-1-</span>), dois últimos dígitos do ano e complemento do Tipo eram <strong>pinados à mão</strong>."]),
  ("h3","Era nacional (1960–1969)"),
  ("ul",["<strong>1960</strong> é o primeiro ano da plaqueta nacional (<span class=\"mono\">INDÚSTRIA BRASILEIRA</span>) — mas nos primeiros meses ainda saíram Fuscas com a plaqueta alemã de 1959.",
         "Passa a <strong>2 rebites</strong>; a partir de <strong>dez/1961</strong> pina-se também a letra <span class=\"mono\">B</span> após \"Chassis Nº\".",
         "No Brasil o Tipo era sempre <span class=\"mono\">3</span> — só existia a versão <strong>Luxo</strong>."]),
  ("h3","Duas plaquetas: 1300 e 1500 (1970–1986)"),
  ("ul",["Com o <strong>Fusca 1500 (agosto/1970)</strong>, a VW passou a usar <strong>duas plaquetas</strong> — por causa da diferença de pesos máximos.",
         "Chassi do <strong>1300 começa com <span class=\"mono\">BJ</span></strong>; o do <strong>1500 com <span class=\"mono\">BS</span></strong>. De out/72 as letras passam a vir pré-estampadas.",
         "De <strong>1993 a 1996</strong> (Fusca Itamar), a plaqueta de identificação <strong>deixa de equipar</strong> o carro."]),
  ("fotos",["FOTO: plaqueta alemã de ferro, 4 rebites (1950–59)","FOTO: plaqueta nacional BJ/BS (1970–86)"]),
  ("box","ex","Exemplo de leitura rápida","Plaqueta de <strong>ferro, 4 rebites lisos</strong>, texto em alemão? → 1950-59. Com <span class=\"mono\">INDÚSTRIA BRASILEIRA</span> e <strong>2 rebites</strong>? → a partir de 1960. Chassi pré-estampado com <span class=\"mono\">BS</span>? → Fusca 1500, de out/72 em diante."),
  ("h2pb","1.5","A outra plaqueta: a da carroceria"),
  ("p","Não confunda com a de identificação. A <strong>plaqueta da carroceria</strong> é uma segunda chapa, introduzida pela VW do Brasil em <strong>meados de janeiro de 1973</strong>, fixada por <strong>2 rebites</strong> na borda superior da <strong>saia dianteira</strong>."),
  ("table",["Geração","O que traz"],[
    ["Até março/1973","ausência de plaqueta na saia dianteira"],
    ["Primeiras plaquetas","4 dígitos, só o tipo de carroceria (<span class=\"mono\">5000</span> = 1500; <span class=\"mono\">4200</span> = 1300)"],
    ["Segunda geração","passa a incluir o <strong>código da cor</strong> do veículo"],
    ["A partir de 1977","padrão de <strong>10 dígitos</strong> (cor + tipo, com zeros à esquerda)"]]),
  ("fotos",["FOTO: plaqueta da carroceria na saia dianteira","FOTO: detalhe do código de cor na plaqueta"]),
  ("box","dica","Por que essa plaqueta vale ouro","O <strong>código da cor</strong> é o dado mais valioso: permite conferir se o carro ainda está na cor de fábrica ou se foi repintado. É a base do Módulo 6."),
  ("h2","1.6","Sinais de alerta na numeração"),
  ("ul",["<strong>Numeração remarcada:</strong> dígitos com espaçamento, profundidade ou tipografia fora do padrão da época.",
         "<strong>Solda/remendo no túnel</strong> justo na região do número — possível enxerto de assoalho.",
         "<strong>Plaqueta fora do padrão do ano</strong> (rebites errados, posição incoerente).",
         "<strong>Suspensão dianteira sem número</strong> → quadro trocado.",
         "<strong>Chassi ≠ plaqueta</strong> → alerta máximo."]),
  ("box","atencao","Regra de ouro","Originalidade sem <strong>identidade legítima</strong> não vale nada. Um Fusca \"todo original\" sobre uma identidade duvidosa é um problema, não um tesouro."),
  ("chk","Checklist de datação — leve na vistoria",[
    "Localizei e fotografei o <strong>número de chassi</strong> no túnel.",
    "Achei a <strong>plaqueta de identificação</strong> e conferi se o chassi <strong>bate</strong>.",
    "Observei a <strong>marcação física</strong> do túnel (ressalto / rebaixo / liso).",
    "Anotei o <strong>número do motor</strong> (sem esperar que \"case\").",
    "Verifiquei o <strong>número da suspensão dianteira</strong>.",
    "Identifiquei a <strong>era da plaqueta</strong>.",
    "Li o <strong>código da cor</strong> (se houver plaqueta de carroceria).",
    "Procurei <strong>sinais de remarcação</strong>."]),
 ]})

# ============================ MÓDULO 2 ============================
MODULOS.append({
 "file":"modulo2.html","pill":"Módulo 2 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 2","title_hi":"Evolução Ano a Ano",
 "sub":"Reconhecer cada fase do Fusca pela aparência — e casar a \"cara\" do carro com a chapa",
 "foot_left":"Do split ao corujão · 1938–1996",
 "sections":[
  ("h2","2.0","A janela traseira: o maior símbolo da evolução"),
  ("lead","Se há um detalhe que sozinho já data um Fusca, é o vigia traseiro. O formato da janela de trás marca as grandes fases do besouro."),
  ("p","Neste módulo você aprende a reconhecer a fase de produção só de bater o olho — e a checar se essa \"cara\" combina com o que a chapa disse no Módulo 1. Quando a aparência e a datação contam histórias diferentes, acende o sinal de alerta."),
  ("h2","2.1","Split, Brezel e Zwitter (até 1953)"),
  ("p","Os Fuscas com <strong>duas janelinhas traseiras</strong> (1938 até março de 1953) são os <strong>split window</strong> (janela bipartida). Na Alemanha, esse carro é chamado de <strong>Brezel</strong> — nome do pão típico do sul alemão, cujo laço lembra os dois vidros. Para os mais rigorosos, \"Brezel\" é só o fabricado até outubro de 1952, por causa da mudança no painel a partir de então."),
  ("table",["Fase","Período","Marca registrada"],[
    ["Split / Brezel","1938 – out/1952","dois vidros traseiros; painel antigo"],
    ["Zwitter (\"híbrido\")","out/1952 – mar/1953","ainda bipartido, mas já com o painel novo"],
    ["Oval","a partir de mar/1953","vidro traseiro único, oval"]]),
  ("box","ex","Exemplo","Viu dois vidrinhos atrás mas o painel já é do tipo novo? É um <strong>Zwitter</strong> — a rara transição de poucos meses entre o split e o oval. Detalhe que muito \"conhecedor\" não sabe reconhecer."),
  ("fotos",["FOTO: traseira split window (dois vidros)","FOTO: traseira oval (vidro único)"]),
  ("h2","2.2","Do oval ao corujão"),
  ("p","A partir de 1953, o Fusca ganha o <strong>vidro oval único</strong>. Com o tempo, a janela vai crescendo em etapas — o vigia fica retangular e cada vez maior — até chegar ao <strong>corujão</strong>, o Fusca de vidro traseiro grande da fase dos anos 70. A regra é simples: <strong>quanto maior o vidro traseiro, mais recente o carro</strong>."),
  ("box","dica","Dica","Use o vidro traseiro como \"relógio\" grosseiro: bipartido = até 53; oval = anos 50; retangular médio = anos 60; grande (corujão) = anos 70 em diante. Depois refine com os outros detalhes."),
  ("h2","2.3","Os marcos do Fusca nacional"),
  ("p","No Brasil, alguns anos concentram mudanças que definem gerações inteiras. Decorá-los é meio caminho para datar qualquer Fusca nacional:"),
  ("table",["Ano","O que mudou"],[
    ["1959","início da produção nacional"],
    ["1967","sistema elétrico passa de <strong>6V para 12V</strong>, vidro traseiro maior, seta vai para a coluna de direção e chega o motor <strong>1300</strong>"],
    ["1970","<strong>Fusca 1500</strong> (o \"Fuscão\"): novas tampas de motor e capô, novos parachoques, bitola traseira mais larga"],
    ["1974","motor <strong>1600</strong> de dupla carburação, para-brisa maior, ventilação interna e pisca-alerta"],
    ["1986","fim da primeira fase de produção nacional"],
    ["1993–1996","volta do Fusca (\"Fusca Itamar\"), já sem a plaqueta de identificação"]]),
  ("box","ex","Exemplo de coerência","Um carro anunciado como \"1972\" mas com faróis de facho assimétrico só, seta no painel e 6V? Contradição: em 1967 já era 12V e seta na coluna. Ou a datação está errada, ou o carro foi muito descaracterizado."),
  ("h2","2.4","Apelidos e o vocabulário do fusqueiro"),
  ("p","Saber o \"dialeto\" ajuda a conversar e a comprar. Os principais:"),
  ("ul",["<strong>Besouro / Fusca:</strong> o apelido consagrado do VW Sedan (Type 1).",
         "<strong>Split / Brezel:</strong> o de janela traseira bipartida.",
         "<strong>Zwitter:</strong> a transição bipartido-com-painel-novo (1952–53).",
         "<strong>Oval:</strong> a geração de vidro traseiro oval.",
         "<strong>Corujão:</strong> o de vidro traseiro grande dos anos 70.",
         "<strong>Fuscão:</strong> o 1500/1600, mais largo e potente, dos anos 70."]),
  ("fotos",["FOTO: comparativo de tamanhos do vidro traseiro por fase","FOTO: dianteira do Fuscão (1500/1600)"]),
  ("chk","Checklist de identificação de fase",[
    "Classifiquei o carro pelo <strong>vidro traseiro</strong> (split / oval / corujão).",
    "Conferi se a fase visual <strong>combina com a datação</strong> do Módulo 1.",
    "Verifiquei os marcos nacionais (6V/12V, 1300/1500/1600).",
    "Anotei incoerências entre \"cara\" e chapa para investigar."]),
 ]})

# ============================ MÓDULO 3 ============================
MODULOS.append({
 "file":"modulo3.html","pill":"Módulo 3 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 3","title_hi":"Carroceria & Detalhes Externos",
 "sub":"Qual peça externa é correta para cada ano — e como flagrar a reposição errada",
 "foot_left":"Parachoques, faróis, espelhos, calotas e frisos",
 "sections":[
  ("h2","3.0","O diabo mora nos detalhes externos"),
  ("lead","É nos pequenos itens de fora — o formato do parachoque, o tipo de calota, a presença ou não do espelho — que o olhar treinado separa o carro original do \"montado\"."),
  ("p","Aqui você aprende a reconhecer os detalhes externos corretos de cada fase e a identificar quando algo é reposição fora de época."),
  ("h2","3.1","Parachoques e batentes"),
  ("p","O parachoque acompanha as fases do Fusca: dos modelos <strong>retos e lisos</strong> das primeiras décadas aos que ganharam <strong>sobre-guarnições</strong> (as famosas \"bananinhas\") e batentes de borracha. O formato, a altura e a presença desses batentes ajudam a datar o carro."),
  ("box","ex","Exemplo","\"Bananinhas\" (sobre-guarnições no parachoque) num Fusca dos anos 50 é anacronismo. Já num carro dos anos 70, a ausência delas pode indicar troca por parachoque de fase anterior."),
  ("h2","3.2","Faróis e lanternas"),
  ("p","Faróis e, principalmente, <strong>lanternas traseiras</strong> mudaram de tamanho e desenho ao longo dos anos — e são um dos itens mais fáceis de datar. As lanternas foram crescendo com o tempo; comparar o desenho da lanterna com a fase do carro é conferência básica."),
  ("fotos",["FOTO: parachoque reto liso (fase antiga)","FOTO: parachoque com batentes/\"bananinhas\" (fase 70)"]),
  ("h2","3.3","Espelho retrovisor externo: um marco de 1969"),
  ("p","Detalhe que pega muita gente: até <strong>1968</strong> o Fusca vinha de fábrica <strong>sem espelho externo</strong>. Era comum a própria concessionária instalar um (do tipo \"pino de porta\", do catálogo de acessórios). O espelho só virou <strong>equipamento de série em 1969</strong>."),
  ("p","Os primeiros de 1969 tinham uma <strong>haste mais comprida</strong> entre a base e o suporte, o que lhes rendeu o apelido de <strong>\"espelho de bracinho\"</strong>."),
  ("box","dica","Dica de originalidade","Um Fusca até 68 \"original\" com espelho de fábrica é contradição — nessa época não existia espelho de série. Se tem, foi acessório de concessionária ou item posterior."),
  ("h2pb","3.4","Calotas: metal, plástico e o \"copinho\""),
  ("p","Das décadas de 1950 a meados de 1970, as calotas eram de <strong>metal</strong>, com o emblema VW no centro — <strong>cromadas</strong> nas versões Luxo e <strong>pintadas</strong> nas Standard. A partir de 1972 a VW do Brasil começou a introduzir <strong>calotas plásticas</strong> (as \"copinho\"); no Fusca, a copinho chegou no <strong>último trimestre de 1973</strong>."),
  ("table",["Tipo de calota","Fase / uso"],[
    ["Metal cromada, emblema VW","versões Luxo, anos 50 a 70"],
    ["Metal pintada, emblema VW","versões Standard, anos 50 a 70"],
    ["Plástica \"copinho\"","no Fusca a partir do último trimestre de 1973"]]),
  ("fotos",["FOTO: calota de metal com emblema VW","FOTO: calota plástica \"copinho\""]),
  ("h2","3.5","Frisos, emblemas, vidros e maçanetas"),
  ("ul",["<strong>Frisos e emblemas:</strong> presença, material e desenho variam por versão (Standard × Luxo) e por ano.",
         "<strong>Brasão do capô:</strong> desenho e fixação mudam com o tempo — bom item de conferência.",
         "<strong>Vidros e borrachas:</strong> com ou sem friso na borracha, formato dos cantos.",
         "<strong>Maçanetas externas:</strong> das antigas de \"gatilho\" às de apertar; o tipo data o carro."]),
  ("box","atencao","Cuidado com o \"kit descaracterização\"","Rebaixado, rodas de liga, faróis de milha, lanternas fumê... nada disso é original. Ótimo para um carro de rua personalizado, mas derruba o valor de um carro avaliado por originalidade."),
  ("chk","Checklist de detalhes externos",[
    "Parachoques e batentes conferem com a fase do carro.",
    "Desenho das lanternas combina com o ano.",
    "Presença/ausência de espelho coerente (série só a partir de 1969).",
    "Calotas corretas (metal × copinho conforme a fase).",
    "Frisos, emblemas, brasão do capô e maçanetas de época.",
    "Sem itens de descaracterização (rodas, faróis, lanternas não originais)."]),
 ]})

# ============================ MÓDULO 4 ============================
MODULOS.append({
 "file":"modulo4.html","pill":"Módulo 4 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 4","title_hi":"Motor & Conjunto de Época",
 "sub":"O motor correto de cada fase e o que descaracteriza a originalidade mecânica",
 "foot_left":"1200 · 1300 · 1500 · 1600 · câmbio e suspensões",
 "sections":[
  ("h2","4.0","O coração refrigerado a ar"),
  ("lead","O motor é a peça que mais troca de carro na vida de um Fusca. Saber qual é o certo para cada ano é o que separa a mecânica original da \"gambiarra de época\"."),
  ("h2","4.1","As cilindradas por fase"),
  ("p","O Fusca brasileiro passou por quatro grandes motorizações. Saber qual corresponde a cada ano é essencial:"),
  ("table",["Motor","Fase (Brasil)","Observações"],[
    ["1200","até 1966","o motor clássico das primeiras fases nacionais; 6V"],
    ["1300","a partir de 1967","chega junto com o 12V"],
    ["1500","a partir de 1970","o \"Fuscão\", ~52 cv"],
    ["1600","a partir de 1974","dupla carburação, ~65 cv"]]),
  ("box","ex","Exemplo","Um 1968 \"original\" deveria ter o 1300 e sistema 12V. Se aparece com 1600 de dupla carburação, o motor é posterior — comum e aceitável para rodar, mas não conta como originalidade mecânica."),
  ("h2","4.2","Lendo o número e o tipo do motor"),
  ("p","O número do motor fica <strong>no bloco</strong>, visível ao abrir a tampa traseira. Como o motor troca com facilidade, ele quase nunca \"casa\" com o chassi — o que importa é confirmar se o <strong>tipo</strong> de motor é compatível com a fase do carro. Lembre: até 1949 a numeração ficava acima da inscrição <span class=\"mono\">Zündfolge 1-4-3-2</span>; depois, abaixo."),
  ("h2","4.3","6 volts × 12 volts"),
  ("p","Um divisor de águas: até 1966 o Fusca era <strong>6V</strong>; a partir de <strong>1967</strong>, <strong>12V</strong>. Gerador, bobina, faróis e buzina acompanham essa mudança. Um carro pós-67 \"original\" rodando em 6V (ou vice-versa) merece investigação."),
  ("fotos",["FOTO: número do motor no bloco","FOTO: motor 1600 refrigerado a ar (compartimento)"]),
  ("h2","4.4","Carburação, afogador e admissão"),
  ("p","A alimentação evoluiu do <strong>carburador simples</strong> à <strong>dupla carburação</strong> do 1600. O <strong>afogador</strong> (usado de 1950 a 1996) e o coletor de admissão têm formatos próprios por fase. Peças de admissão fora de época são pistas de motor trocado."),
  ("h2","4.5","Câmbio e suspensões"),
  ("ul",["<strong>Caixa de câmbio:</strong> tem número próprio na carcaça e evoluiu (ex.: câmbios bipartidos nas fases antigas). A localização do número varia por ano e tipo.",
         "<strong>Suspensão dianteira:</strong> quadro com numeração própria (só os originais a têm) — ver Módulo 1.",
         "<strong>Sistema de ar quente:</strong> o aquecimento do Fusca usa o ar aquecido pelo motor, com dutos e caixa de ar próprios; itens de época ajudam na originalidade."]),
  ("box","dica","Dica","No motor, procure a coerência do conjunto: gerador/alternador, carburação, tampas e chapas de ar (antirruído do compartimento) compatíveis com a fase. Um detalhe fora avisa que o resto pode estar também."),
  ("chk","Checklist do conjunto mecânico",[
    "A cilindrada é compatível com a fase do carro (1200/1300/1500/1600).",
    "Sistema elétrico coerente (6V até 66; 12V de 67 em diante).",
    "Carburação e admissão compatíveis com o motor.",
    "Número do motor localizado e anotado.",
    "Câmbio e suspensões com numeração/tipo de época.",
    "Sistema de ar quente e chapas do compartimento presentes."]),
 ]})

# ============================ MÓDULO 5 ============================
MODULOS.append({
 "file":"modulo5.html","pill":"Módulo 5 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 5","title_hi":"Interior Original",
 "sub":"Reconhecer o interior de fábrica de cada fase — do painel ao forro de porta",
 "foot_left":"Bancos, painel, volante e acabamentos",
 "sections":[
  ("h2","5.0","Por dentro, a verdade aparece"),
  ("lead","O interior é onde o tempo mais deixa marcas — e onde mais se improvisa. Reconhecer o que é de fábrica separa a restauração séria do \"remendo bonito\"."),
  ("h2","5.1","Bancos e forração"),
  ("p","Os bancos mudam bastante por fase: dos <strong>bancos dianteiros do split</strong> às versões posteriores, passando pelos populares <strong>\"gomão\"</strong> e pelos <strong>inteiriços</strong>. Material, costura e desenho do encosto ajudam a datar. Cuidado com bancos esportivos de reposição (concha, reclinável de fornecedores diversos) — descaracterizam o carro original."),
  ("box","ex","Exemplo","Bancos tipo concha e reclináveis de marcas de acessório são ótimos para conforto, mas num carro avaliado por originalidade contam contra: o correto é o banco de fábrica da fase."),
  ("h2","5.2","Painel, instrumentos e volante"),
  ("p","O <strong>painel</strong> mudou cedo (a transição do Brezel para o Zwitter, em 1952, já marca um painel novo) e seguiu evoluindo. O <strong>volante</strong> acompanha: dos modelos antigos ao volante <strong>\"cálice\"</strong>, com seu botão de buzina característico. Os <strong>botões de painel com logo VW</strong> e o desenho dos instrumentos são bons itens de conferência."),
  ("fotos",["FOTO: painel e volante \"cálice\"","FOTO: banco de fábrica da fase (ex.: gomão)"]),
  ("h2","5.3","Acabamentos e itens de época"),
  ("ul",["<strong>Bolsa da forração lateral</strong> e forros de porta: desenho evolui por fase.",
         "<strong>Tapetes e forrações:</strong> material e cor de fábrica variam por ano.",
         "<strong>Maçanetas internas, manivelas e puxadores:</strong> tipo data o carro.",
         "<strong>Relógio de horas:</strong> acessório de época muito procurado.",
         "<strong>Capas Copacabana:</strong> item de época clássico do interior do Fusca."]),
  ("box","dica","Dica","Fotografe o interior inteiro na vistoria: painel, bancos, forros, tapetes e teto. Detalhes internos fora de época são dos sinais mais reveladores de que o carro foi \"refeito\" sem compromisso com originalidade."),
  ("chk","Checklist do interior",[
    "Bancos de fábrica compatíveis com a fase (sem esportivos de reposição).",
    "Painel e instrumentos coerentes com o ano.",
    "Volante correto da fase (ex.: cálice).",
    "Forros, tapetes e acabamentos de época.",
    "Maçanetas internas e manivelas do tipo correto.",
    "Itens de época (relógio, capas) avaliados à parte."]),
 ]})

# ============================ MÓDULO 6 ============================
MODULOS.append({
 "file":"modulo6.html","pill":"Módulo 6 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 6","title_hi":"Cores Originais",
 "sub":"Dominar os códigos de cor e provar se o carro está na cor de fábrica",
 "foot_left":"Códigos de cor · nacionais, alemãs e metálicas",
 "sections":[
  ("h2","6.0","A cor conta uma história"),
  ("lead","Poucos itens valorizam (ou desvalorizam) tanto um Fusca quanto a cor. Estar na cor original de fábrica é um dos maiores trunfos de originalidade — e dá para provar."),
  ("h2","6.1","Como funciona o código de cor"),
  ("p","Cada cor de fábrica tem um <strong>código</strong>. Nos Fuscas de origem alemã, o sistema usa a letra <span class=\"mono\">L</span> seguida de números (por exemplo, um azul <span class=\"mono\">L36</span> ou um vermelho <span class=\"mono\">L351</span>). Esse código é a \"impressão digital\" da cor."),
  ("p","No Fusca nacional, a partir de 1973 o código da cor passou a constar na <strong>plaqueta da carroceria</strong> (ver Módulo 1). Com ele, você compara o que a fábrica pintou com o que está no carro hoje."),
  ("box","ex","Exemplo","A plaqueta da carroceria indica o código de um azul específico, mas o carro está branco. Conclusão direta: <strong>foi repintado</strong> em cor diferente da de fábrica. Isso muda a avaliação — e o preço."),
  ("h2","6.2","Cores nacionais e alemãs"),
  ("p","As paletas mudaram ao longo dos anos e diferem entre o Fusca alemão e o nacional. Cada fase teve seu conjunto de cores disponíveis; uma cor \"certa\" para 1972 pode não existir no catálogo de 1965. As <strong>tabelas de cores por ano</strong> (que compõem o material de consulta deste módulo) são a ferramenta para checar se a cor é plausível para o ano do carro."),
  ("fotos",["FOTO: leque/tabela de cores do Fusca por ano","FOTO: código de cor sob a borracha/vão (cor original preservada)"]),
  ("h2","6.3","Cores metálicas e combinações"),
  ("p","Além das cores sólidas, houve <strong>cores metálicas</strong> e combinações especiais em determinadas fases. Elas têm códigos próprios e, por serem menos comuns, pedem atenção redobrada — tanto pela raridade quanto pela facilidade de serem imitadas por repintura."),
  ("h2","6.4","Detectando repintura"),
  ("p","Como descobrir a cor original mesmo num carro repintado:"),
  ("ul",["<strong>Código na plaqueta</strong> da carroceria: a fonte primária.",
         "<strong>Vãos e áreas escondidas:</strong> sob borrachas, dentro das portas, no vão do motor e do porta-malas, a cor original costuma sobreviver.",
         "<strong>Batentes e canaletas:</strong> lugares que o repintador \"esquece\".",
         "<strong>Sob a forração:</strong> pontos internos revelam a tonalidade de fábrica."]),
  ("box","dica","Dica de ouro","Sempre cruze três coisas: o <strong>código da plaqueta</strong>, a <strong>cor aparente</strong> e a <strong>cor nos vãos escondidos</strong>. Quando os três batem, você tem um forte indício de cor original preservada."),
  ("chk","Checklist de cor original",[
    "Li o <strong>código de cor</strong> na plaqueta da carroceria.",
    "Conferi se a cor é <strong>plausível para o ano</strong> (tabela do módulo).",
    "Procurei a cor original em <strong>vãos e áreas escondidas</strong>.",
    "Cruzei código × cor aparente × cor dos vãos.",
    "Registrei se há repintura e se manteve (ou não) a cor de fábrica."]),
 ]})

# ============================ MÓDULO 7 ============================
MODULOS.append({
 "file":"modulo7.html","pill":"Módulo 7 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 7","title_hi":"Acessórios de Época",
 "sub":"Diferenciar NOS, reposição e réplica — e conhecer os acessórios que valorizam o carro",
 "foot_left":"Marcas, bagageiros, \"veneno de época\" e raridades",
 "sections":[
  ("h2","7.0","O universo que valoriza o Fusca"),
  ("lead","Acessórios de época são a alma do colecionismo. Um item raro e original pode valer mais que muita peça grande — desde que você saiba distinguir o legítimo do \"parece\"."),
  ("h2","7.1","NOS × reposição × réplica"),
  ("p","Três categorias que todo avaliador precisa separar:"),
  ("table",["Categoria","O que é"],[
    ["<strong>NOS</strong> (New Old Stock)","peça original de fábrica/época, nunca usada — o mais valioso"],
    ["<strong>Original usada</strong>","peça de fábrica/época, com uso — legítima, valor conforme o estado"],
    ["<strong>Reposição</strong>","peça nova fabricada depois, para repor — funcional, valor menor"],
    ["<strong>Réplica / \"china\"</strong>","cópia recente, muitas vezes de menor qualidade — cuidado"]]),
  ("box","ex","Exemplo","Um farol auxiliar de marca de época, com a marcação do fabricante e o código correto, é NOS ou original. A mesma \"cara\" sem marcação, plástico novo e rosca diferente é réplica — vale uma fração."),
  ("h2","7.2","As marcas que você precisa conhecer"),
  ("p","Reconhecer as marcas de época e suas marcações é o que permite datar e autenticar um acessório:"),
  ("ul",["<strong>Hella, Bosch:</strong> iluminação, buzinas, elétrica — marcações e códigos ajudam a datar.",
         "<strong>Kamei:</strong> acessórios aerodinâmicos e de estilo (defletores, spoilers de época).",
         "<strong>EMPI:</strong> acessórios e performance, muito valorizados.",
         "<strong>Norfol, e demais fornecedores oficiais VW:</strong> itens do catálogo original.",
         "<strong>Abarth</strong> e outros: escapes e \"venenos\" de época."]),
  ("fotos",["FOTO: acessório de época com marcação do fabricante","FOTO: bagageiro de época montado no Fusca"]),
  ("h2pb","7.3","Bagageiros, camping e \"veneno de época\""),
  ("p","Categoria queridíssima dos colecionadores:"),
  ("ul",["<strong>Bagageiros</strong> (dianteiros e traseiros) de marcas de época (Bekowa, Brasiliense, GHE...).",
         "<strong>Itens de camping e viagem:</strong> barracas, apoios e utilidades de época.",
         "<strong>\"Veneno de época\":</strong> escapes esportivos, carburação e acessórios de performance <em>da época</em> — que, por serem de época, agregam em vez de descaracterizar.",
         "<strong>Utilidades de bordo:</strong> acendedor, relógio, aspirador, cafeteira e outras curiosidades originais."]),
  ("box","dica","Dica","\"Veneno\" moderno descaracteriza; \"veneno de época\" valoriza. A diferença é a data e a marca do acessório. Aprenda a ler as marcações — é o que autentica a peça."),
  ("h2","7.4","Raridades e como datar um acessório"),
  ("p","Os itens <strong>\"rarest of the rare\"</strong> — acessórios raríssimos de catálogo — são o topo do colecionismo. Para autenticar qualquer acessório, procure: <strong>marca do fabricante</strong>, <strong>número/código de peça</strong>, <strong>tipo de material e acabamento</strong> compatíveis com a época, e presença em <strong>catálogos oficiais</strong> de acessórios."),
  ("chk","Checklist de acessórios",[
    "Classifiquei cada item: NOS / original usada / reposição / réplica.",
    "Procurei <strong>marca e código</strong> do fabricante na peça.",
    "Confirmei material e acabamento compatíveis com a época.",
    "Verifiquei se o item consta em catálogo oficial de acessórios.",
    "Separei \"veneno de época\" (valoriza) de item moderno (descaracteriza)."]),
 ]})

# ============================ MÓDULO 8 ============================
MODULOS.append({
 "file":"modulo8.html","pill":"Módulo 8 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 8","title_hi":"Avaliação & Compra",
 "sub":"Aplicar tudo numa vistoria real: avaliar originalidade e não cair em armadilha",
 "foot_left":"Checklist mestre · armadilhas · precificação",
 "sections":[
  ("h2","8.0","A hora da verdade"),
  ("lead","Todo o curso converge aqui: pegar um Fusca de verdade, na garagem de um vendedor, e dizer com segurança o quanto ele é original — e quanto vale por isso."),
  ("h2","8.1","O checklist mestre de originalidade"),
  ("p","Uma vistoria de originalidade percorre, nesta ordem, o que você aprendeu:"),
  ("ul",["<strong>Identidade</strong> (Mód. 1): chassi = plaqueta, marcação do túnel, numeração sã.",
         "<strong>Fase</strong> (Mód. 2): a \"cara\" do carro bate com a datação.",
         "<strong>Externo</strong> (Mód. 3): parachoques, faróis, espelho, calotas, frisos.",
         "<strong>Mecânica</strong> (Mód. 4): motor compatível, 6V/12V, câmbio e suspensões.",
         "<strong>Interior</strong> (Mód. 5): bancos, painel, volante, acabamentos.",
         "<strong>Cor</strong> (Mód. 6): código da plaqueta × cor aparente × vãos.",
         "<strong>Acessórios</strong> (Mód. 7): o que é NOS, original, reposição ou réplica."]),
  ("h2","8.2","As armadilhas mais comuns"),
  ("table",["Armadilha","Como flagrar"],[
    ["\"Documento certinho\", carro repintado","cruze o código de cor da plaqueta com a cor atual"],
    ["Motor \"casado\" que não bate com a fase","confira o tipo do motor, não só o número"],
    ["Peças de reposição vendidas como originais","procure marca, código e acabamento de época"],
    ["Chassi remarcado","tipografia, profundidade e solda na região do número"],
    ["\"Todo original\" com detalhes fora de fase","use os checklists dos módulos 2 a 7"]]),
  ("box","atencao","Regra de ouro da compra","Desconfie do \"tá tudo original\" dito de boca. Originalidade se <strong>prova</strong> item a item. Se o vendedor recusa que você levante o banco traseiro para ver o chassi, já sabe o que fazer."),
  ("h2","8.3","Documentação e procedência"),
  ("p","Além da chapa, pesam a <strong>documentação</strong> (coerência entre chassi, motor e CRLV), a <strong>procedência</strong> (histórico, dono anterior, notas) e, quando existe, o registro em <strong>concessionária</strong> ou clube. Um carro com história documentada vale mais — e engana menos."),
  ("fotos",["FOTO: vistoria — leitura do chassi sob o banco","FOTO: dossiê/documentação do veículo"]),
  ("h2","8.4","Precificando pela originalidade"),
  ("p","Originalidade é valor. Ao fechar a avaliação, pese: <strong>grau de originalidade</strong> (quantos itens de fábrica preservados), <strong>raridade da fase/versão/cor</strong>, <strong>estado de conservação</strong> e <strong>qualidade da eventual restauração</strong>. Monte um <strong>dossiê</strong> com fotos e anotações — ele justifica o preço e fecha negócio."),
  ("chk","Checklist mestre de compra",[
    "Rodei os checklists dos Módulos 1 a 7.",
    "Cruzei documento, cor e numerações.",
    "Investiguei procedência e histórico.",
    "Classifiquei o grau de originalidade do carro.",
    "Montei o dossiê com fotos e anotações.",
    "Cheguei a uma faixa de preço justificada."]),
 ]})

# ============================ MÓDULO 9 ============================
MODULOS.append({
 "file":"modulo9.html","pill":"Módulo 9 de 9","tag":"Curso Fusca Original · Apostila",
 "title_main":"Módulo 9","title_hi":"Restaurar sem Descaracterizar",
 "sub":"Restaurar preservando a originalidade — o que manter, recuperar ou repor",
 "foot_left":"Filosofia, decisões e certificação",
 "sections":[
  ("h2","9.0","Restaurar é decidir"),
  ("lead","Toda restauração é uma sequência de escolhas. Feitas com critério, valorizam o carro; feitas no impulso, apagam para sempre o que fazia dele um original."),
  ("h2","9.1","Originalidade × restauro × customização"),
  ("p","Três filosofias, três resultados: o <strong>preservacionista</strong> mantém tudo o que der (até a pátina); o <strong>restaurador</strong> recupera ao estado de fábrica; o <strong>customizador</strong> personaliza. Nenhuma é errada — mas só as duas primeiras preservam valor de originalidade. Decida <em>antes</em> de começar."),
  ("box","ex","Exemplo","Trocar o assoalho inteiro por um novo resolve a ferrugem, mas apaga a marcação original do chassi no túnel. Às vezes, recuperar o trecho vale mais que substituir a peça inteira."),
  ("h2","9.2","O que sempre preservar"),
  ("ul",["<strong>Numerações de fábrica:</strong> chassi, plaquetas, número do motor e da suspensão.",
         "<strong>Chapas com marcação original</strong> (o túnel, principalmente).",
         "<strong>Vestígios da cor original</strong> nos vãos (documente antes de repintar).",
         "<strong>Peças de época em bom estado:</strong> recupere antes de substituir.",
         "<strong>Acessórios originais:</strong> nunca descarte sem avaliar."]),
  ("h2","9.3","Reposição correta e cor de fábrica"),
  ("p","Quando repor for inevitável, escolha a peça <strong>correta para a fase</strong> (não a genérica mais barata). Na pintura, o ideal é <strong>manter o código de cor de fábrica</strong> — mudar a cor, mesmo por uma bonita, reduz a originalidade. Guarde as peças originais substituídas: elas fazem parte da história do carro."),
  ("fotos",["FOTO: antes e depois de uma restauração preservando originalidade","FOTO: peça original recuperada × reposição nova"]),
  ("h2","9.4","Erros que derrubam o valor"),
  ("ul",["Repintar em cor diferente da de fábrica sem registrar a original.",
         "Substituir o assoalho apagando a marcação do chassi.",
         "Trocar bancos e volante por itens esportivos de reposição.",
         "Instalar rodas, faróis e lanternas não originais.",
         "Descartar peças e acessórios originais \"velhos\"."]),
  ("h2","9.5","Certificação e veículo de coleção"),
  ("p","Um carro restaurado com critério pode buscar <strong>certificação de originalidade</strong> junto a entidades e clubes especializados. Além de reconhecimento, a certificação vira um <strong>ativo</strong>: documenta a originalidade e valoriza o carro na hora da venda. É o coroamento do trabalho bem-feito."),
  ("box","dica","Dica final","Documente cada etapa da restauração com fotos e notas. Esse registro é ouro: prova o que foi preservado, justifica o valor e conta a história do seu Fusca."),
  ("chk","Checklist de restauração consciente",[
    "Defini a filosofia (preservar / restaurar / customizar) antes de começar.",
    "Preservei todas as numerações e chapas com marcação.",
    "Documentei a cor original antes de qualquer pintura.",
    "Escolhi reposições corretas para a fase.",
    "Guardei as peças originais substituídas.",
    "Registrei cada etapa com fotos para o dossiê.",
    "Avaliei buscar certificação de originalidade."]),
 ]})

# ============================ BÔNUS ============================
MODULOS.append({
 "file":"bonus.html","pill":"Bônus","tag":"Curso Fusca Original · Material Extra",
 "title_main":"Bônus","title_hi":"A Família Refrigerada a Ar",
 "sub":"Estendendo o método de originalidade para os outros aircooled da Volkswagen",
 "foot_left":"Kombi · Brasília · Variant · Karmann Ghia",
 "sections":[
  ("h2","B.0","O mesmo olhar, outros modelos"),
  ("lead","O método que você aprendeu — datar pela chapa, casar a fase com a aparência, autenticar peças e cores — vale para toda a família refrigerada a ar da VW."),
  ("p","Este bônus é um aperitivo: mostra como aplicar o mesmo raciocínio de originalidade nos irmãos do Fusca. Cada um deles renderia um curso próprio."),
  ("h2","B.1","Kombi"),
  ("p","A perua eterna da VW tem sua própria evolução (das \"corujinhas\" às fases seguintes), plaquetas, cores e um <strong>universo enorme de acessórios</strong> de época. Os princípios de identificação e originalidade são os mesmos do Fusca."),
  ("h2","B.2","Brasília e Variant"),
  ("p","Projetos nacionais sobre a mesma base mecânica refrigerada a ar. Têm datação, cores e detalhes de originalidade próprios — e um público colecionador crescente."),
  ("h2","B.3","Karmann Ghia"),
  ("p","O cupê elegante sobre mecânica de Fusca. Raro e valorizado, exige atenção especial à originalidade de carroceria, interior e acessórios."),
  ("fotos",["FOTO: Kombi clássica","FOTO: Karmann Ghia"]),
  ("box","dica","Convite","Gostou do método? Estes modelos podem virar os próximos cursos da Aircooled Market — o mesmo rigor de originalidade, aplicado a toda a família aircooled."),
 ]})
